### PR TITLE
[UPD] l10n_nl_rgs: Updated values for Inkopen - BTW verlegd (21%) tax and added Inkopen - BTW verlegd (9%) tax

### PR DESCRIPTION
**Pull request by ByteMeAsap**

### CODE REVIEW

**Comment by ByteMeAsap** [comment]
Do we also need to add mappings in fiscal position for 9% tax like for 21%
Screenshot from 2024-04-24 17-18-31

**Review by andreschenkels — COMMENTED** [review]
This looks good but as @ByteMeAsap asked. We also need to add the 9% verlegd in the fiscal position mappings.

**Comment by ByteMeAsap** [comment]
> This looks good but as @ByteMeAsap asked. We also need to add the 9% verlegd in the fiscal position mappings.

@andreschenkels , Added the 9% verlegd in the fiscal position mappings as well

**Comment by ThijsvOers** [comment]
@ByteMeAsap the tax group is not correct for the group BTW verlegd. It is Nul (zero) in the standard, but maybe you can combine this with the other request I had to create a new Tax Group BTW Verlegd (applicable to all the BTW verlegd VAT codes
image

**Comment by ByteMeAsap** [comment]
@ThijsvOers , I have added the tax group, but that would need to manually adjusted on the taxes

@andreschenkels , I have added the migration script, but it will be to add new taxes , update fiscal positions , but only update tags for existing taxes

**Review by ThijsvOers — APPROVED** [review]
Checked this and both 21 and 9% VAT reversed charge are now correct

**Review by andreschenkels — APPROVED** [review]
This one can be merged now.

**Pull request merged**
